TaskManagement/Controllers/ProjectUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Model;

namespace TaskManagement.Controllers
{
    [Authorize(Roles = "Администратор")]
    public class ProjectUserController : Controller
    {
        private TaskManagementDBEntities db = new TaskManagementDBEntities();

        private int projectId
        {
            get
            {
                return TempData["ProjectId"] != null ? Convert.ToInt32(TempData["ProjectId"]) : 0;
            }
            set
            {
                TempData["ProjectId"] = value;
            }
        }
        // GET: ProjectUser
        public ActionResult Index(int projectId)
        {
            this.projectId = projectId;
            var projectUsers = db.ProjectUsers.Where(x => x.ProjectId == projectId).Include(p => p.AspNetUser).Include(p => p.Project);
            return View(projectUsers.ToList());
        }

        // GET: ProjectUser/Create
        public ActionResult Create()
        {
            var projectUserIds = db.ProjectUsers.Where(x => x.ProjectId == projectId).Select(x => x.UserId);
            ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x => !projectUserIds.Contains(x.Id)), "Id", "Email");

            var role = db.AspNetRoles.FirstOrDefault(x => x.Id == "2");
            var roles = new List<SelectListItem>();
            roles.Add(new SelectListItem() { Value = role.Id, Text = role.Name });
            roles.Add(new SelectListItem() { Value = "", Text = "Не выбрано" });
            ViewBag.RoleId = roles;

            return View();
        }

        // POST: ProjectUser/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ProjectId,RoleId, UserId,CreateDate")] ProjectUser projectUser)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(projectUser.RoleId)) projectUser.RoleId = null;
                projectUser.CreateDate = DateTime.Now;
                db.ProjectUsers.Add(projectUser);
                db.SaveChanges();
                return RedirectToAction("Index", new { projectId = projectUser.ProjectId });
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", projectUser.UserId);
            return View(projectUser);
        }

        // GET: ProjectUser/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectUser projectUser = db.ProjectUsers.Find(id);
            if (projectUser == null)
            {
                return HttpNotFound();
            }
            return View(projectUser);
        }

        // POST: ProjectUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProjectUser projectUser = db.ProjectUsers.Find(id);
            db.ProjectUsers.Remove(projectUser);
            db.SaveChanges();
            return RedirectToAction("Index", new { projectId = projectUser.ProjectId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TaskManagement/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Model;
using Microsoft.AspNet.Identity;

namespace TaskManagement.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private TaskManagementDBEntities db = new TaskManagementDBEntities();

        // GET: Task
        public ActionResult Index(int projectId = 0, string orderBy = "", int status = 2)
        {
            var userId = this.User.Identity.GetUserId();
            ViewBag.ProjectId = projectId;
            ViewBag.StatusId = status;
            ViewBag.CanCRUD = CanCRUD(projectId);

            var tasks = db.Tasks.Include(t => t.Project).Include(t => t.TaskStatus);
            if (projectId > 0) tasks = tasks.Where(x => x.ProjectId == projectId);

            var dtNow = DateTime.Now.Date;

            if (!this.User.IsInRole("Администратор"))
            {
                var userProjects = db.ProjectUsers.Where(x => x.UserId == userId && x.RoleId == "2").Select(x => x.ProjectId);
                if (userProjects.Any())
                {
                    tasks = tasks.Where(x => userProjects.Contains(x.ProjectId));
                }
                else
                {
                    tasks = tasks.Where(x => x.ExecutorId == userId);
                }
            }

            if (!string.IsNullOrEmpty(orderBy))
            {
                switch (orderBy.ToLower())
                {
                    case "project": tasks = tasks.OrderBy(x => x.ProjectId); break;
                    case "user": tasks = tasks.OrderBy(x => x.ExecutorId); break;
                    case "status": tasks = tasks.OrderBy(x => x.StatusId); break;
                    default: break;
                }
            }

            switch (status)
            {
                case (int)TaskStatuses.ToDo: tasks = tasks.Where(x => x.StatusId == status && x.StartDate > dtNow); break;
                case (int)TaskStatuses.InProgress: tasks = tasks.Where(x => x.StatusId == (int)TaskStatuses.InProgress || (x.StatusId == (int)TaskStatuses.ToDo && x.StartDate <= dtNow && x.EndDate >= dtNow)); break;
                case (int)TaskStatuses.Done: tasks = tasks.Where(x => x.StatusId == status); break;
                case (int)TaskStatuses.All: break;
                case (int)TaskStatuses.NextWeek:
                    var nextWeekStart = GetNextWeekday(DateTime.Today, DayOfWeek.Monday);
                    var nextWeekEnd = GetNextWeekday(DateTime.Today, DayOfWeek.Sunday);
                    tasks = tasks.Where(x => x.StatusId == (int)TaskStatuses.ToDo && x.StartDate >= nextWeekStart && x.StartDate <= nextWeekEnd);
                    break;
                default: break;
            }
            return View(tasks.ToList());
        }

        private DateTime GetNextWeekday(DateTime start, DayOfWeek day)
        {
            int daysToAdd = ((int)day - (int)start.DayOfWeek + 7) % 7;
            return start.AddDays(daysToAdd);
        }

        private DateTime GetCurrentWeekday(DateTime start, DayOfWeek day)
        {
            int daysToAdd = ((int)day - (int)start.DayOfWeek) % 7;
            return start.AddDays(daysToAdd);
        }

        private bool CanCRUD(int projectId)
        {
            if (this.User.IsInRole("Администратор")) return true;
            var userId = this.User.Identity.GetUserId();
            var userProjects = db.ProjectUsers.Where(x => x.UserId == userId && x.RoleId == "2").Select(x => x.ProjectId);
            if (userProjects.Any())
            {
                return userProjects.Contains(projectId);
            }
            return false;
        }

        // GET: Task/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        [HttpPost]
        public ActionResult Details(Task task)
        {
            Task old = db.Tasks.Find(task.Id);
            if (task == null)
            {
                return HttpNotFound();
            }
            old.StatusId = task.StatusId;

            var log = new TaskStatusLog();
            log.TaskId = task.Id;
            log.StatusId = task.StatusId;
            log.CreateDate = DateTime.Now;
            db.TaskStatusLogs.Add(log);

            db.SaveChanges();

            return View(task);
        }

        // GET: Task/Create
        public ActionResult Create(int projectId)
        {
            if (!CanCRUD(projectId)) throw new Exception("У вас нет разрешения на эту страницу");
            ViewBag.ProjectId = projectId;
            ViewBag.ExecutorId = new SelectList(db.ProjectUsers.Where(x => x.ProjectId == projectId).Select(x => x.AspNetUser), "Id", "Email");
            ViewBag.StatusId = new SelectList(db.TaskStatuses, "Id", "Name");
            return View();
        }

        // POST: Task/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description,ProjectId,ExecutorId,StartDate,EndDate,StatusId")] Task task)
        {
            if (!CanCRUD(task.ProjectId)) throw new Exception("У вас нет разрешения на эту страницу");
            if (ModelState.IsValid)
            {
                task.CreatorId = this.User.Identity.GetUserId();
                task.CreateDate = DateTime.Now;
                db.Tasks.Add(task);
                db.SaveChanges();
                return RedirectToAction("Index", new { projectId = task.ProjectId });
            }

            ViewBag.ExecutorId = new SelectList(db.AspNetUsers, "Id", "Email", task.ExecutorId);
            ViewBag.StatusId = new SelectList(db.TaskStatuses, "Id", "Name", task.StatusId);
            return View(task);
        }

        // GET: Task/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (!CanCRUD(task.ProjectId)) throw new Exception("У вас нет разрешения на эту страницу");
            if (task == null)
            {
                return HttpNotFound();
            }

            ViewBag.ExecutorId = new SelectList(db.AspNetUsers, "Id", "Email", task.ExecutorId);
            ViewBag.StatusId = new SelectList(db.TaskStatuses, "Id", "Name", task.StatusId);
            return View(task);
        }

        // POST: Task/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,ProjectId,ExecutorId,StartDate,EndDate,StatusId,CreateDate")] Task task)
        {
            if (!CanCRUD(task.ProjectId)) throw new Exception("У вас нет разрешения на эту страницу");
            if (ModelState.IsValid)
            {
                var old = db.Tasks.Where(x => x.Id == task.Id).FirstOrDefault();
                old.ModifiedDate = DateTime.Now;
                old.Title = task.Title;
                old.Description = task.Description;
                old.StartDate = task.StartDate;
                old.EndDate = task.EndDate;
                old.ExecutorId = task.ExecutorId;
                if(old.StatusId!= task.StatusId)
                {
                    var log = new TaskStatusLog();
                    log.TaskId = old.Id;
                    log.CreateDate = DateTime.Now;
                    log.StatusId = task.StatusId;
                    db.TaskStatusLogs.Add(log);
                }

                old.StatusId = task.StatusId;
                db.SaveChanges();
                return RedirectToAction("Index", new { projectId = task.ProjectId });
            }

            ViewBag.ExecutorId = new SelectList(db.AspNetUsers, "Id", "Email", task.ExecutorId);
            ViewBag.StatusId = new SelectList(db.TaskStatuses, "Id", "Name", task.StatusId);
            return View(task);
        }

        // GET: Task/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (!CanCRUD(task.ProjectId)) throw new Exception("У вас нет разрешения на эту страницу");
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Task/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Task task = db.Tasks.Find(id);
            if (!CanCRUD(task.ProjectId)) throw new Exception("У вас нет разрешения на эту страницу");
            db.Tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Index", new { projectId = task.ProjectId });
        }

        [ChildActionOnly]
        public ActionResult Statistics()
        {
            var monday = (DateTime.Now.DayOfWeek != DayOfWeek.Monday) ? GetCurrentWeekday(DateTime.Now, DayOfWeek.Monday) : DateTime.Now;
            var sunday = (DateTime.Now.DayOfWeek != DayOfWeek.Sunday) ? GetNextWeekday(DateTime.Now, DayOfWeek.Sunday) : DateTime.Now;

TaskManagement/Views/Project/Create.cshtml
@model TaskManagement.Model.Project

@{
    ViewBag.Title = "Добавление нового проекта";
}

<h2>Добавление нового проекта</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Проект</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskManagement/Views/Project/Delete.cshtml
@model TaskManagement.Model.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TaskManagement/Views/Project/Details.cshtml
@model TaskManagement.Model.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TaskManagement/Views/Project/Edit.cshtml
@model TaskManagement.Model.Project

@{
    ViewBag.Title = "Редактирование проекта";
}

<h2>Редактирование проекта</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Проект</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskManagement/Views/Project/Index.cshtml
@model IEnumerable<TaskManagement.Model.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (this.User.IsInRole("Администратор"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        <th>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                @if (this.User.IsInRole("Администратор"))
                {
                    <span>
                        @Html.ActionLink("Участники", "Index", "ProjectUser", new { projectId = item.Id }, null) |
                    </span>
                }

                @Html.ActionLink("Задачи", "Index", "Task", new { projectId = item.Id }, null)
            </td>

            <td>
                @if (this.User.IsInRole("Администратор"))
                {
                    <span>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </span>
                }
            </td>
        </tr>
    }

</table>